# Introduction

The Clearinghouse for Financing Development Data aims to provide a dedicated platform for aid 
providers and recipients to align their priorities, optimise their decision-making and demonstrate 
a stronger case for data and statistics. To reach this goal, the platform prioritises user-focused, 
transparent and accessible information about partners, projects and results, which will build on 
timely, accurate and in-depth data. 

This is the first platform offering a holistic overview over both, the financial support to statistics 
and data as well as the financing needs in partner countries. For these reasons, the project team 
sourced in project-level data on financing for development statistics from a wide range of data 
stakeholders, including international organisations, development cooperation providers, statistical 
offices and line ministries. The Clearinghouse project team received strategic guidance on the data 
sourcing process from the Bern Network (see [Data Sourcing Strategic Note | April 2021](https://smartdatafinance.org/storage/2021-09-29/KHIclbojuRz5L9b.pdf)). 

This technical note gives an overview over the implementation of the data sourcing process. It is 
directed at development data experts interested in the collection and processing of financing data 
on development data. Chapter \@ref(financing-dev-data) introduces the most important terminology on financing. Chapter 
\@ref(about-the-data) illustrates the data collection and processing of the various data flows.