# ABOUT FINANCING FOR DEVELOPMENT DATA {#financing-dev-data}

Data are crucial for development because they are at the core of the type of evidence-based policy-
making that improves people’s lives and are at the heart of the 2030 Agenda. National statistical
systems (NSS) gather, analyse and share data - on births and deaths, growth and poverty, taxes
and trade, land and the environment, and sickness, schooling and safety - that governments, the
private sector and civil society need to set priorities, target policies and investments, and make
informed choices to advance sustainable development and efforts to build back better. Recent
research has highlighted this role of data for sustainable development (e.g. [WDR 2021](https://www.worldbank.org/en/publication/wdr2021)).
Financing for development data is defined here as a sub-set of development finance. Development
finance can include different types of support directed at supporting low-and middle income
countries. It goes beyond official development aid (ODA) and can include private and philanthropic
financing flows.

Official development assistance (ODA) is defined by the OECD Development Assistance Committee
(DAC) as government aid that promotes and specifically targets the economic development
and welfare of low-and middle income countries. It refers to financial support - either grants or
“concessional” loans from OECD-DAC member countries to low-and middle income countries.
These funds are provided to advance development in areas such as health, sanitation, education,
infrastructure, and strengthening tax systems and administrative capacity, among others. The [DAC list of countries eligible to receive ODA](https://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/daclist.htm) is updated every three years and is based on per capita
income ([OECD, 2021](https://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/What-is-ODA.pdf)).

Since the Monterrey Consensus in 2002, questions about broader development finance, including
how to best mobilise private resources for development, have been at the heart of the political
debate on development finance. This includes, inter alia, private and public funding mobilised
through development finance, export credits, foreign direct investment, remittances and the
mobilisation of institutional investors ([OECD, 2021](https://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/What-is-ODA.pdf)).

In the Clearinghouse Platform, we aim to give a holistic picture of financing specifically targeted
at statistics and data in IDA countries. This includes the financial support from development
providers (see \@ref(financial-support-statistics-data)), the financing opportunities in statistical systems (see \@ref(funding-opp-stat-system)), the overall statistical
performance in recipient countries (see \@ref(stat-performance)) and the specific sectoral support to gender data and
statistics (see \@ref(gender-financing)).

## Financial Support to Statistics and Data {#financial-support-statistics-data}

Financial support to data and statistics refers to any type of support international development
cooperation actors target at specific projects on data and statistics in low-and middle income
countries.

### Bilateral versus multilateral support

Financial support to data and statistics can come from bilateral and multilateral development
actors.

Bilateral finance comes directly from a single country or institution in that country. One example
would be a case where the government of Sweden via the Swedish International Development
Agency (SIDA) commits 1 million USD to the Uganda’s government to implement a project on
improving statistical literacy.^[This is a purely hypothetical case to illustrate bilateral funding.]

Multilateral sources are public finance institutions that have multiple countries as contributors
or shareholders, which bring together funding contributions from these different countries, and
where decisions on the use of funds are typically taken by the institution. Often, funding provided
through multilaterals can be earmarked by the funding country for specific purposes. Earmarked
funding accounted for about 35% of multilateral contributions in 2018 (OECD, 2020). Examples
include the World Bank, the IMF, multilateral development banks or UN agencies.

Most DAC member states provide both bilateral and multilateral financial support to low-and
middle income countries. The Clearinghouse displays data on both types of support. However, due
to the nature of multilateral support, it is at times very difficult to trace back the original funding
source of a project. Let’s take the example of a project financed by the [World Bank Trust Fund for Statistical Capacity Building (TFSCB)](https://blogs.worldbank.org/opendata/what-tfscb). Financing is pooled from various bilateral sources and then
committed to a specific program targeted at a region. In the reporting system of the OECD, this
project is then reported as financed by the UK. The project is labelled as bilateral funding that is
channelled through the World Bank. In this case, we do not know which recipient actual received
the financial support.^[This is a purely hypothetical case to illustrate the potential problem of double counting.]

In other cases, multilateral funding can be traced back to the recipient. For instance, the UK gives
money to UNWOMEN to implement a gender data visualization workshop with the Bureau of
Statistics in Uganda. This financing flow is also recorded as bilateral funding in the OECD reporting
system, however the recipient in this case Uganda and the channel UNWOMEN.^[This is a purely hypothetical case to illustrate the potential problem of double counting.]

### Different types and instruments of financial support

Financial support can be issued both “on-budget” and “off-budget” support. On-budget support
usually refers to development cooperation funding that is recorded in the annual budgets approved
by the legislatures of low-and middle income countries.

“Off-budget support” is often more difficult to trace because it refers to assistance provided by a
donor and/or implementing agency that bypasses the core national budget and over which the
government has no control. This type of support is often not adequately reflected in the central
government budget of a recipient country. Typically, this includes direct technical assistance such
as equipment or trainings. In the Clearinghouse, we intend to mark both, on- and off budget
support provided by development cooperation providers.

Furthermore, development cooperation providers use a range of financing instruments to provide
support. The Clearinghouse covers grants and loans, which are the instruments most used by
development cooperation providers for statistics. Grants refer to transfers of funding for which no
repayment is required. A development loan is a short-term loan advanced towards achieving specific
objectives. The required funds are issued in stages or drawdown payments upon completion of
pre-agreed works.

### Commitments and disbursements

In some data sources (most notably the Creditor Reporting System published by the OECD),
commitments are reported separately from disbursements. The definitions below are based on
the [DAC Glossary](https://www.oecd.org/dac/dac-glossary.htm).

**Commitments**. A firm obligation, expressed in writing and backed by the necessary funds, which
is undertaken by an official donor. It provides specified assistance to a recipient country or a
multilateral organisation. Bilateral commitments are recorded in the full amount of the expected
transfer, irrespective of the time required for the completion of disbursements. Commitments to
multilateral organisations are reported as the sum of (i) any disbursements in the year reported
on, which have not previously been notified as commitments, and (ii) expected disbursements in
the following year.

**Disbursements**. The release of funds to or the purchase of goods or services for a recipient;
by extension, the amount spent. Disbursements record the actual international transfer of
financial resources, or of goods or services valued at the cost to the donor. In the case of activities
conducted in donor countries, such as training, administration, or public awareness programs,
disbursement is assumed to have occurred when the funds have been transferred to the service
provider or recipient. These may be recorded as gross (the total amount disbursed over a given
accounting period) or net (the gross amount, less any repayments of loan principal or recoveries
on grants received during the same period).

This separation in reporting offers more explanation on the processes behind financing for
development data. On the donor side, a delay between when commitments are finalized and when
disbursements are made is common, because it takes time to implement the approved projects.
Sometimes, it may take up to several years to disburse a commitment.




## Funding Opportunities in Statistical Systems {#funding-opp-stat-system}

The analysis of financing opportunities in statistical systems is the most challenging and novel data
element the Clearinghouse presents. We refer here to data on the budgets of statistical offices and
related entities inside the national statistical systems.

### Capturing the financial situation in statistical countries

The most intutive way of capturing the financial situation of government entities is to analyse
their budget tables. Budget tables are often not published in a transparent fashion and specifically
difficult to access for statistical systems for three main reasons.

First, many statistical systems do not operate in a centralized manner, but coordinate across
decentralized data production entities. In Malawi for instance, the national statistical office only
overlooks a share of the statistical budget. Other ministries have their own budget for statistics
and data. In these cases, the budget overview needs to be analysed using budget tables from a
variety of different statistical entities, with the most relevant often being the national planning
commission, or the ministry of finance of the respective country.

Second, there are varying degrees of institutional capacity. Statistical systems in low-and middle-
income countries usually rely on a mix of domestic government and external sources of money,
coming from donors or other financial institutions. Reporting the different streams into budgets
often proves difficult. Countries may record an inflow of financing in their budget, however, due
to low absorptive capacity, may not be able to actually spend the amount committed. Another
problematic situation is when the donor disbursement is delayed in countries that are very reliant
on external support. Sometimes the country is left without necessary funds before the money is
disbursed. For instance, this can lead to underfunded statistical systems in Q1 of a fiscal year, and
then to an overfunding in subsequent months, which is often overwhelming for the institution at
the receiving end. Often, these granularities are not recorded accordingly, leading to oddly high
numbers in some years, and no records in others.

A third issue refers to currency standards in budget tables. Especially in countries that rely
extensively on donor support, currencies are often not harmonized and some amounts are
received in USD while others are displayed in local currencies. This leads to further difficulties
when assessing budget gaps and defining where money is missing in the statistical system.
The Clearinghouse project team worked closely with international organisations such as the World
Bank and the UN Statistical Division to design the careful collection of country data displayed in
the recipient profiles. In addition, we launched four pilot assessments to get a clearer picture of
the diversity of financing to data and statistics on the ground. Our partner countries were critical
in verifying and validating the data we collected via various channels.


### Latent need for financing to statistics and data

Moving beyond budget tables, the Clearinghouse also assesses the expressed and latent demand
for financing. This refers to the need for support which is not visible via budget gaps in the reporting
by the government or statistical entity, but rather to abstract needs that are either intangible (e.g.
need for upskilling a specific division in the statistical office) or that lay ahead in the future (e.g.
support targeted at policy sectors in the next three years).

The results from these assessments are visible in the recipient profiles, but also on our dedicated
gender channel.

## Statistical Performance {#stat-performance}

Benchmarks of statistical performance, such as the Statistical Performance Indicators published
by the World Bank or the Statistical Capacity Monitor by PARIS21 are a major starting point for
development providers to target their financial support more effectively.

In the Clearinghouse, we report key indicators that benchmark statistical performance overall, and
along the data value chain (including aspects of data planning, production, dissemination and use)
to provider further guidance to donors

## Gender Data Financing {#gender-financing}

Gender data is defined by the [UN Statistics Division](https://unstats.un.org/unsd/demographic-social/Standards-and-Methods/files/Handbooks/gender/Integrating-a-Gender-Perspective-into-Statistics-E.pdf) as data that are collected and presented by
sex as a primary and overall classification, data that reflect gender issues, data that are based on
concepts and definitions that adequately reflect the diversity of women and men and capture
all aspects of their lives, and as data that are collected using methods that take into account
stereotypes and social and cultural factors that may induce gender bias in the data. Research by
several actors, including UN Women, Data2X, and ODW has shown that large gaps exist for gender
data and that more and better data are needed in order to achieve the SDG promise of leaving no
one behind.

Financing for gender data is defined here as the domestic and external support to building gender
data systems. These do not exist separately from robust overall statistical systems but rather
complement them; robust gender data systems and information systems are intertwined. Yet we
focus on gender data financing for another reason: Just as there is a gap in the available data for
women, men, girl, and boys, there is a large gap in the financing required to fill these data gaps. The
[State of Gender Data Financing 2021 report](https://data2x.org/resource-center/state-of-gender-data-financing-2021/) by Data2X and ODW finds that gender data systems
have been underfunded by $450 million per year since 2015 and in order to fully fund gender data
systems by 2030, roughly $1 billion is required from donors and countries.

In the Clearinghouse, we describe gender data financing flows to IDA countries from external sources
as captured by ODA commitments, described in section \@ref(financial-support-statistics-data), gender data financing opportunities in
these countries as captured by domestic statistical capacity planning documents, as well as gender-
relevant statistical instrument production and performance on statistical capacity indicators. Using
these three blocks of information, we ensure that domestic and external providers of gender data
financing are able to more effectively target and build better gender data systems.
