# ABOUT THE DATA 



## FINANCIAL SUPPORT TO STATISTICS AND DATA


### PARIS21 – PRESS data

### OECD – Data for Development Profiles

#### Limitations of the data

#### What did we do to the data to make it usable for the Clearinghouse



## FUNDING OPPORTUNITIES IN STATISTICAL SYSTEMS


### UNSD – World Bank – PARIS21 Cape Town Global Action Plan Implementation Survey

#### Limitations of the data

#### What did we do to the data to make it usable for the Clearinghouse?


### PARIS21 - Pilot assessments

#### Limitations of the data

#### What did we do to the data to make it usable for the Clearinghouse?



## STATISTICAL PERFORMANCE     


### World Bank – Statistical Performance Indicators

#### Limitations of the data

#### What did we do to the data to make it usable for the Clearinghouse?


### Open Data Watch - Open Data Inventory

#### Limitations of the data

#### What did we do to the data to make it usable for the Clearinghouse?


## GENDER DATA FINANCING


### PRESS gender data financing projects 

#### Limitations of the data

#### What did we do to the data to make it usable for the Clearinghouse?


### Gender-relevant survey inventory

#### Limitations of the data

#### What did we do to the data to make it usable for the Clearinghouse?


### Gender data-relevant indices

#### Limitations of the data

#### What did we do to the data to make it usable for the Clearinghouse?


### Domestic financing for gender data

#### Limitations of the data

#### What did we do to the data to make it usable for the Clearinghouse?